<?php

/**
 * Master:: object
 *
 * Template (HTML) generation helper; Autoloads single static Master:: object
 * to give us access to slightly advanced 'view' loading and variable passing
 * 
 * Created 2012 by Adam Kiss
 * Licensed under WTFPL (http://sam.zoy.org/wtfpl/)
 * 
 * http://www.adamkiss.com
 */

class HelperMaster extends WireData implements Module {

	/**
	 * Z informationz
	 *
	 * @return array
	 */
	public static function getModuleInfo() {

		return array(
			'title' => 'Master::',
			'version' => 002, 
			'summary' => 'Advanced templating – Including self-encapsulated views and passing variables to them has never been easier',
			'href' => 'http://www.adamkiss.com',
			'singular' => true, 
			'autoload' => true, 
		);
	}

	// We don't really need to do anything else here; this file is now autoloaded
	// thus below we can add another object, that will be 'automagically' loaded
	// for use in templates
	//
	// booyah!
}

require "HelperMaster_Template.php";
require "HelperMaster_Master.php";